export var data = [
	{
		"Restaurant_ID": 6317637,
		"Restaurant_Name": "Le Petit Souffle",
		"Cuisines": "French, Japanese, Desserts",
		"Average_Cost_for_two": 1100,
		"Currency": "Botswana Pula(P)",
		"Has_Table_booking": "Yes",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.8,
		"Rating_color": "Dark Green",
		"Rating_text": "Excellent",
		"Votes": 314
	},
	{
		"Restaurant_ID": 6304287,
		"Restaurant_Name": "Izakaya Kikufuji",
		"Cuisines": "Japanese",
		"Average_Cost_for_two": 1200,
		"Currency": "Botswana Pula(P)",
		"Has_Table_booking": "Yes",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.5,
		"Rating_color": "Dark Green",
		"Rating_text": "Excellent",
		"Votes": 591
	},
	{
		"Restaurant_ID": 6300002,
		"Restaurant_Name": "Heat - Edsa Shangri-La",
		"Cuisines": "Seafood, Asian, Filipino, Indian",
		"Average_Cost_for_two": 4000,
		"Currency": "Botswana Pula(P)",
		"Has_Table_booking": "Yes",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.4,
		"Rating_color": "Green",
		"Rating_text": "Very Good",
		"Votes": 270
	},
	{
		"Restaurant_ID": 6318506,
		"Restaurant_Name": "Ooma",
		"Cuisines": "Japanese, Sushi",
		"Average_Cost_for_two": 1500,
		"Currency": "Botswana Pula(P)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.9,
		"Rating_color": "Dark Green",
		"Rating_text": "Excellent",
		"Votes": 365
	},
	{
		"Restaurant_ID": 6314302,
		"Restaurant_Name": "Sambo Kojin",
		"Cuisines": "Japanese, Korean",
		"Average_Cost_for_two": 1500,
		"Currency": "Botswana Pula(P)",
		"Has_Table_booking": "Yes",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.8,
		"Rating_color": "Dark Green",
		"Rating_text": "Excellent",
		"Votes": 229
	},
	{
		"Restaurant_ID": 18189371,
		"Restaurant_Name": "Din Tai Fung",
		"Cuisines": "Chinese",
		"Average_Cost_for_two": 1000,
		"Currency": "Botswana Pula(P)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.4,
		"Rating_color": "Green",
		"Rating_text": "Very Good",
		"Votes": 336
	},
	{
		"Restaurant_ID": 6300781,
		"Restaurant_Name": "Buffet 101",
		"Cuisines": "Asian, European",
		"Average_Cost_for_two": 2000,
		"Currency": "Botswana Pula(P)",
		"Has_Table_booking": "Yes",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4,
		"Rating_color": "Green",
		"Rating_text": "Very Good",
		"Votes": 520
	},
	{
		"Restaurant_ID": 6301290,
		"Restaurant_Name": "Vikings",
		"Cuisines": "Seafood, Filipino, Asian, European",
		"Average_Cost_for_two": 2000,
		"Currency": "Botswana Pula(P)",
		"Has_Table_booking": "Yes",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.2,
		"Rating_color": "Green",
		"Rating_text": "Very Good",
		"Votes": 677
	},
	{
		"Restaurant_ID": 6300010,
		"Restaurant_Name": "Spiral - Sofitel Philippine Plaza Manila",
		"Cuisines": "European, Asian, Indian",
		"Average_Cost_for_two": 6000,
		"Currency": "Botswana Pula(P)",
		"Has_Table_booking": "Yes",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.9,
		"Rating_color": "Dark Green",
		"Rating_text": "Excellent",
		"Votes": 621
	},
	{
		"Restaurant_ID": 6314987,
		"Restaurant_Name": "Locavore",
		"Cuisines": "Filipino",
		"Average_Cost_for_two": 1100,
		"Currency": "Botswana Pula(P)",
		"Has_Table_booking": "Yes",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.8,
		"Rating_color": "Dark Green",
		"Rating_text": "Excellent",
		"Votes": 532
	},
	{
		"Restaurant_ID": 6309903,
		"Restaurant_Name": "Silantro Fil-Mex",
		"Cuisines": "Filipino, Mexican",
		"Average_Cost_for_two": 800,
		"Currency": "Botswana Pula(P)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.9,
		"Rating_color": "Dark Green",
		"Rating_text": "Excellent",
		"Votes": 1070
	},
	{
		"Restaurant_ID": 6309455,
		"Restaurant_Name": "Mad Mark's Creamery & Good Eats",
		"Cuisines": "American, Ice Cream, Desserts",
		"Average_Cost_for_two": 900,
		"Currency": "Botswana Pula(P)",
		"Has_Table_booking": "Yes",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.2,
		"Rating_color": "Green",
		"Rating_text": "Very Good",
		"Votes": 488
	},
	{
		"Restaurant_ID": 6318433,
		"Restaurant_Name": "Silantro Fil-Mex",
		"Cuisines": "Filipino, Mexican",
		"Average_Cost_for_two": 800,
		"Currency": "Botswana Pula(P)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.8,
		"Rating_color": "Dark Green",
		"Rating_text": "Excellent",
		"Votes": 294
	},
	{
		"Restaurant_ID": 6310470,
		"Restaurant_Name": "Guevarra's",
		"Cuisines": "Filipino",
		"Average_Cost_for_two": 1000,
		"Currency": "Botswana Pula(P)",
		"Has_Table_booking": "Yes",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.2,
		"Rating_color": "Green",
		"Rating_text": "Very Good",
		"Votes": 458
	},
	{
		"Restaurant_ID": 6314605,
		"Restaurant_Name": "Sodam Korean Restaurant",
		"Cuisines": "Korean",
		"Average_Cost_for_two": 700,
		"Currency": "Botswana Pula(P)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.3,
		"Rating_color": "Green",
		"Rating_text": "Very Good",
		"Votes": 223
	},
	{
		"Restaurant_ID": 18185059,
		"Restaurant_Name": "Cafe Arabelle",
		"Cuisines": "Cafe, American, Italian, Filipino",
		"Average_Cost_for_two": 800,
		"Currency": "Botswana Pula(P)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 3.6,
		"Rating_color": "Yellow",
		"Rating_text": "Good",
		"Votes": 29
	},
	{
		"Restaurant_ID": 18182702,
		"Restaurant_Name": "Nonna's Pasta & Pizzeria",
		"Cuisines": "Italian, Pizza",
		"Average_Cost_for_two": 850,
		"Currency": "Botswana Pula(P)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4,
		"Rating_color": "Green",
		"Rating_text": "Very Good",
		"Votes": 72
	},
	{
		"Restaurant_ID": 6318213,
		"Restaurant_Name": "Balay Dako",
		"Cuisines": "Filipino",
		"Average_Cost_for_two": 1200,
		"Currency": "Botswana Pula(P)",
		"Has_Table_booking": "Yes",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.5,
		"Rating_color": "Dark Green",
		"Rating_text": "Excellent",
		"Votes": 211
	},
	{
		"Restaurant_ID": 18255654,
		"Restaurant_Name": "Hobing Korean Dessert Cafe",
		"Cuisines": "Cafe, Korean, Desserts",
		"Average_Cost_for_two": 600,
		"Currency": "Botswana Pula(P)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.5,
		"Rating_color": "Dark Green",
		"Rating_text": "Excellent",
		"Votes": 118
	},
	{
		"Restaurant_ID": 6308205,
		"Restaurant_Name": "Wildflour Cafe + Bakery",
		"Cuisines": "Cafe, Bakery, American, Italian",
		"Average_Cost_for_two": 1500,
		"Currency": "Botswana Pula(P)",
		"Has_Table_booking": "Yes",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.4,
		"Rating_color": "Green",
		"Rating_text": "Very Good",
		"Votes": 392
	},
	{
		"Restaurant_ID": 6315438,
		"Restaurant_Name": "NIU by Vikings",
		"Cuisines": "Seafood, American, Mediterranean, Japanese",
		"Average_Cost_for_two": 3000,
		"Currency": "Botswana Pula(P)",
		"Has_Table_booking": "Yes",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.7,
		"Rating_color": "Dark Green",
		"Rating_text": "Excellent",
		"Votes": 535
	},
	{
		"Restaurant_ID": 6310406,
		"Restaurant_Name": "The Food Hall by Todd English",
		"Cuisines": "American, Asian, Italian, Seafood",
		"Average_Cost_for_two": 1800,
		"Currency": "Botswana Pula(P)",
		"Has_Table_booking": "Yes",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.5,
		"Rating_color": "Dark Green",
		"Rating_text": "Excellent",
		"Votes": 618
	},
	{
		"Restaurant_ID": 6600681,
		"Restaurant_Name": "Chez Michou",
		"Cuisines": "Fast Food, French",
		"Average_Cost_for_two": 55,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 3,
		"Rating_color": "Orange",
		"Rating_text": "Average",
		"Votes": 6
	},
	{
		"Restaurant_ID": 6601005,
		"Restaurant_Name": "Caf� Daniel Briand",
		"Cuisines": "Cafe",
		"Average_Cost_for_two": 30,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 3.8,
		"Rating_color": "Yellow",
		"Rating_text": "Good",
		"Votes": 9
	},
	{
		"Restaurant_ID": 6600292,
		"Restaurant_Name": "Casa do Biscoito Mineiro",
		"Cuisines": "Bakery",
		"Average_Cost_for_two": 45,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 3.7,
		"Rating_color": "Yellow",
		"Rating_text": "Good",
		"Votes": 11
	},
	{
		"Restaurant_ID": 6600441,
		"Restaurant_Name": "Maori",
		"Cuisines": "Brazilian",
		"Average_Cost_for_two": 60,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 3.8,
		"Rating_color": "Yellow",
		"Rating_text": "Good",
		"Votes": 11
	},
	{
		"Restaurant_ID": 6600970,
		"Restaurant_Name": "Pizza �� Bessa",
		"Cuisines": "Pizza",
		"Average_Cost_for_two": 50,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 3.2,
		"Rating_color": "Orange",
		"Rating_text": "Average",
		"Votes": 11
	},
	{
		"Restaurant_ID": 6600379,
		"Restaurant_Name": "Sushi Loko",
		"Cuisines": "Japanese",
		"Average_Cost_for_two": 80,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 3.1,
		"Rating_color": "Orange",
		"Rating_text": "Average",
		"Votes": 10
	},
	{
		"Restaurant_ID": 6600214,
		"Restaurant_Name": "Beirute",
		"Cuisines": "Arabian",
		"Average_Cost_for_two": 90,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 3.7,
		"Rating_color": "Yellow",
		"Rating_text": "Good",
		"Votes": 8
	},
	{
		"Restaurant_ID": 6601218,
		"Restaurant_Name": "New Koto",
		"Cuisines": "Japanese",
		"Average_Cost_for_two": 200,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 3.7,
		"Rating_color": "Yellow",
		"Rating_text": "Good",
		"Votes": 5
	},
	{
		"Restaurant_ID": 6600060,
		"Restaurant_Name": "Sandubas Caf�",
		"Cuisines": "Brazilian, Cafe",
		"Average_Cost_for_two": 30,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 0,
		"Rating_color": "White",
		"Rating_text": "Not rated",
		"Votes": 2
	},
	{
		"Restaurant_ID": 6600083,
		"Restaurant_Name": "Villa Tevere",
		"Cuisines": "Italian",
		"Average_Cost_for_two": 150,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.1,
		"Rating_color": "Green",
		"Rating_text": "Very Good",
		"Votes": 12
	},
	{
		"Restaurant_ID": 6601515,
		"Restaurant_Name": "Rovereto",
		"Cuisines": "Pizza",
		"Average_Cost_for_two": 100,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 3.1,
		"Rating_color": "Orange",
		"Rating_text": "Average",
		"Votes": 9
	},
	{
		"Restaurant_ID": 6601361,
		"Restaurant_Name": "Buena Carne",
		"Cuisines": "Bar Food, Brazilian",
		"Average_Cost_for_two": 60,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 3.6,
		"Rating_color": "Yellow",
		"Rating_text": "Good",
		"Votes": 9
	},
	{
		"Restaurant_ID": 6601602,
		"Restaurant_Name": "Taco Pep",
		"Cuisines": "Mexican, Grill",
		"Average_Cost_for_two": 100,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.3,
		"Rating_color": "Green",
		"Rating_text": "Very Good",
		"Votes": 29
	},
	{
		"Restaurant_ID": 6601589,
		"Restaurant_Name": "Coco Bambu",
		"Cuisines": "International",
		"Average_Cost_for_two": 230,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.2,
		"Rating_color": "Green",
		"Rating_text": "Very Good",
		"Votes": 17
	},
	{
		"Restaurant_ID": 6601862,
		"Restaurant_Name": "Tayp��",
		"Cuisines": "Peruvian, Latin American",
		"Average_Cost_for_two": 100,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 3.6,
		"Rating_color": "Yellow",
		"Rating_text": "Good",
		"Votes": 5
	},
	{
		"Restaurant_ID": 6601595,
		"Restaurant_Name": "Outback Steakhouse",
		"Cuisines": "American, Grill",
		"Average_Cost_for_two": 150,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4,
		"Rating_color": "Green",
		"Rating_text": "Very Good",
		"Votes": 10
	},
	{
		"Restaurant_ID": 6601158,
		"Restaurant_Name": "Manzu��",
		"Cuisines": "Seafood",
		"Average_Cost_for_two": 240,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 3.2,
		"Rating_color": "Orange",
		"Rating_text": "Average",
		"Votes": 6
	},
	{
		"Restaurant_ID": 6600427,
		"Restaurant_Name": "Coco Bambu",
		"Cuisines": "International",
		"Average_Cost_for_two": 230,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.9,
		"Rating_color": "Dark Green",
		"Rating_text": "Excellent",
		"Votes": 30
	},
	{
		"Restaurant_ID": 6600116,
		"Restaurant_Name": "Gero",
		"Cuisines": "Italian",
		"Average_Cost_for_two": 350,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 3.3,
		"Rating_color": "Orange",
		"Rating_text": "Average",
		"Votes": 8
	},
	{
		"Restaurant_ID": 6601457,
		"Restaurant_Name": "Brazilian American Burgers",
		"Cuisines": "American, Burger",
		"Average_Cost_for_two": 50,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 3.6,
		"Rating_color": "Yellow",
		"Rating_text": "Good",
		"Votes": 9
	},
	{
		"Restaurant_ID": 7303219,
		"Restaurant_Name": "Pesqueiro Eco Gourmet",
		"Cuisines": "Seafood, Bar Food, Brazilian",
		"Average_Cost_for_two": 140,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4,
		"Rating_color": "Green",
		"Rating_text": "Very Good",
		"Votes": 7
	},
	{
		"Restaurant_ID": 7304307,
		"Restaurant_Name": "Confeitaria Colombo",
		"Cuisines": "Desserts, Cafe",
		"Average_Cost_for_two": 100,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.8,
		"Rating_color": "Dark Green",
		"Rating_text": "Excellent",
		"Votes": 29
	},
	{
		"Restaurant_ID": 7301215,
		"Restaurant_Name": "Bibi",
		"Cuisines": "Juices, Healthy Food",
		"Average_Cost_for_two": 60,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.7,
		"Rating_color": "Dark Green",
		"Rating_text": "Excellent",
		"Votes": 24
	},
	{
		"Restaurant_ID": 7300596,
		"Restaurant_Name": "Cervantes",
		"Cuisines": "Beverages, Bar Food, Fast Food",
		"Average_Cost_for_two": 90,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.5,
		"Rating_color": "Dark Green",
		"Rating_text": "Excellent",
		"Votes": 29
	},
	{
		"Restaurant_ID": 7300612,
		"Restaurant_Name": "Amir",
		"Cuisines": "Lebanese",
		"Average_Cost_for_two": 170,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.2,
		"Rating_color": "Green",
		"Rating_text": "Very Good",
		"Votes": 11
	},
	{
		"Restaurant_ID": 7300704,
		"Restaurant_Name": "TT Burger",
		"Cuisines": "Burger",
		"Average_Cost_for_two": 60,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.8,
		"Rating_color": "Dark Green",
		"Rating_text": "Excellent",
		"Votes": 19
	},
	{
		"Restaurant_ID": 7300955,
		"Restaurant_Name": "Braseiro da G��vea",
		"Cuisines": "Brazilian, Bar Food",
		"Average_Cost_for_two": 100,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.9,
		"Rating_color": "Dark Green",
		"Rating_text": "Excellent",
		"Votes": 40
	},
	{
		"Restaurant_ID": 7300521,
		"Restaurant_Name": "Balada Mix",
		"Cuisines": "Brazilian, Healthy Food, Juices, Pizza",
		"Average_Cost_for_two": 90,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.6,
		"Rating_color": "Dark Green",
		"Rating_text": "Excellent",
		"Votes": 21
	},
	{
		"Restaurant_ID": 7300515,
		"Restaurant_Name": "Garota de Ipanema",
		"Cuisines": "Brazilian, Bar Food",
		"Average_Cost_for_two": 120,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.9,
		"Rating_color": "Dark Green",
		"Rating_text": "Excellent",
		"Votes": 49
	},
	{
		"Restaurant_ID": 7300483,
		"Restaurant_Name": "Zaz�� Bistr�� Tropical",
		"Cuisines": "Brazilian",
		"Average_Cost_for_two": 170,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.6,
		"Rating_color": "Dark Green",
		"Rating_text": "Excellent",
		"Votes": 21
	},
	{
		"Restaurant_ID": 7301064,
		"Restaurant_Name": "Fil� de Ouro",
		"Cuisines": "Brazilian",
		"Average_Cost_for_two": 90,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.3,
		"Rating_color": "Green",
		"Rating_text": "Very Good",
		"Votes": 14
	},
	{
		"Restaurant_ID": 7304312,
		"Restaurant_Name": "D.O.C Ristorante",
		"Cuisines": "Italian",
		"Average_Cost_for_two": 150,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4,
		"Rating_color": "Green",
		"Rating_text": "Very Good",
		"Votes": 5
	},
	{
		"Restaurant_ID": 7300004,
		"Restaurant_Name": "Sushi Leblon",
		"Cuisines": "Japanese",
		"Average_Cost_for_two": 250,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.6,
		"Rating_color": "Dark Green",
		"Rating_text": "Excellent",
		"Votes": 25
	},
	{
		"Restaurant_ID": 7300868,
		"Restaurant_Name": "Talho Capixaba",
		"Cuisines": "Bakery, Sandwich, Brazilian",
		"Average_Cost_for_two": 120,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.4,
		"Rating_color": "Green",
		"Rating_text": "Very Good",
		"Votes": 13
	},
	{
		"Restaurant_ID": 7302637,
		"Restaurant_Name": "Leme Light",
		"Cuisines": "Brazilian",
		"Average_Cost_for_two": 40,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.2,
		"Rating_color": "Green",
		"Rating_text": "Very Good",
		"Votes": 7
	},
	{
		"Restaurant_ID": 7302140,
		"Restaurant_Name": "Shirley",
		"Cuisines": "Brazilian, Seafood",
		"Average_Cost_for_two": 250,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.2,
		"Rating_color": "Green",
		"Rating_text": "Very Good",
		"Votes": 8
	},
	{
		"Restaurant_ID": 7305048,
		"Restaurant_Name": "Quiosque Chopp Brahma",
		"Cuisines": "Bar Food, Brazilian",
		"Average_Cost_for_two": 70,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 0,
		"Rating_color": "White",
		"Rating_text": "Not rated",
		"Votes": 1
	},
	{
		"Restaurant_ID": 7302898,
		"Restaurant_Name": "Apraz�_vel",
		"Cuisines": "Brazilian",
		"Average_Cost_for_two": 300,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.7,
		"Rating_color": "Dark Green",
		"Rating_text": "Excellent",
		"Votes": 44
	},
	{
		"Restaurant_ID": 7302859,
		"Restaurant_Name": "Aconchego Carioca",
		"Cuisines": "Brazilian, Bar Food",
		"Average_Cost_for_two": 85,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.6,
		"Rating_color": "Dark Green",
		"Rating_text": "Excellent",
		"Votes": 24
	},
	{
		"Restaurant_ID": 7301700,
		"Restaurant_Name": "Garota de Ipanema",
		"Cuisines": "Brazilian, Bar Food",
		"Average_Cost_for_two": 80,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.3,
		"Rating_color": "Green",
		"Rating_text": "Very Good",
		"Votes": 10
	},
	{
		"Restaurant_ID": 6706313,
		"Restaurant_Name": "Cantina Famiglia Mancini",
		"Cuisines": "Italian, Pizza",
		"Average_Cost_for_two": 250,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.5,
		"Rating_color": "Dark Green",
		"Rating_text": "Excellent",
		"Votes": 49
	},
	{
		"Restaurant_ID": 6704326,
		"Restaurant_Name": "Templo da Carne - Marcos Bassi",
		"Cuisines": "Steak, BBQ",
		"Average_Cost_for_two": 250,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.4,
		"Rating_color": "Green",
		"Rating_text": "Very Good",
		"Votes": 17
	},
	{
		"Restaurant_ID": 6711179,
		"Restaurant_Name": "Gopala Hari",
		"Cuisines": "Indian",
		"Average_Cost_for_two": 70,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 3.1,
		"Rating_color": "Orange",
		"Rating_text": "Average",
		"Votes": 5
	},
	{
		"Restaurant_ID": 6702797,
		"Restaurant_Name": "Jiquitaia",
		"Cuisines": "Brazilian",
		"Average_Cost_for_two": 100,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.1,
		"Rating_color": "Green",
		"Rating_text": "Very Good",
		"Votes": 15
	},
	{
		"Restaurant_ID": 6700475,
		"Restaurant_Name": "Skye - Hotel Unique",
		"Cuisines": "Beverages, International",
		"Average_Cost_for_two": 300,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.8,
		"Rating_color": "Dark Green",
		"Rating_text": "Excellent",
		"Votes": 59
	},
	{
		"Restaurant_ID": 6713413,
		"Restaurant_Name": "Les 3 Brasseurs",
		"Cuisines": "French, Brazilian, Beverages",
		"Average_Cost_for_two": 120,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.6,
		"Rating_color": "Dark Green",
		"Rating_text": "Excellent",
		"Votes": 30
	},
	{
		"Restaurant_ID": 6714340,
		"Restaurant_Name": "Red Steak & Burger",
		"Cuisines": "Brazilian, Grill",
		"Average_Cost_for_two": 75,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 3.9,
		"Rating_color": "Yellow",
		"Rating_text": "Good",
		"Votes": 5
	},
	{
		"Restaurant_ID": 6710645,
		"Restaurant_Name": "Cantinho da Gula",
		"Cuisines": "Brazilian",
		"Average_Cost_for_two": 55,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 0,
		"Rating_color": "White",
		"Rating_text": "Not rated",
		"Votes": 0
	},
	{
		"Restaurant_ID": 6700402,
		"Restaurant_Name": "Paris 6 Classique",
		"Cuisines": "French",
		"Average_Cost_for_two": 200,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 3.4,
		"Rating_color": "Orange",
		"Rating_text": "Average",
		"Votes": 73
	},
	{
		"Restaurant_ID": 6700846,
		"Restaurant_Name": "Kawa Sushi",
		"Cuisines": "Sushi, Japanese",
		"Average_Cost_for_two": 120,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 3.5,
		"Rating_color": "Yellow",
		"Rating_text": "Good",
		"Votes": 9
	},
	{
		"Restaurant_ID": 6702159,
		"Restaurant_Name": "A Figueira Rubaiyat",
		"Cuisines": "BBQ, Grill, Brazilian",
		"Average_Cost_for_two": 300,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.3,
		"Rating_color": "Green",
		"Rating_text": "Very Good",
		"Votes": 39
	},
	{
		"Restaurant_ID": 6711666,
		"Restaurant_Name": "Kinoshita",
		"Cuisines": "Sushi",
		"Average_Cost_for_two": 230,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 3.9,
		"Rating_color": "Yellow",
		"Rating_text": "Good",
		"Votes": 12
	},
	{
		"Restaurant_ID": 6701257,
		"Restaurant_Name": "Meats",
		"Cuisines": "Gourmet Fast Food, Burger",
		"Average_Cost_for_two": 120,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.3,
		"Rating_color": "Green",
		"Rating_text": "Very Good",
		"Votes": 68
	},
	{
		"Restaurant_ID": 6706211,
		"Restaurant_Name": "Paribar",
		"Cuisines": "Brazilian, Italian",
		"Average_Cost_for_two": 150,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.3,
		"Rating_color": "Green",
		"Rating_text": "Very Good",
		"Votes": 46
	},
	{
		"Restaurant_ID": 6705858,
		"Restaurant_Name": "Terra�_o It��lia",
		"Cuisines": "Italian",
		"Average_Cost_for_two": 400,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.4,
		"Rating_color": "Green",
		"Rating_text": "Very Good",
		"Votes": 37
	},
	{
		"Restaurant_ID": 6701419,
		"Restaurant_Name": "Divino Fog�o",
		"Cuisines": "Brazilian, Mineira",
		"Average_Cost_for_two": 65,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 0,
		"Rating_color": "White",
		"Rating_text": "Not rated",
		"Votes": 2
	},
	{
		"Restaurant_ID": 6703956,
		"Restaurant_Name": "Super Grill",
		"Cuisines": "Brazilian",
		"Average_Cost_for_two": 50,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 0,
		"Rating_color": "White",
		"Rating_text": "Not rated",
		"Votes": 2
	},
	{
		"Restaurant_ID": 6709580,
		"Restaurant_Name": "Esquina Mocot�_",
		"Cuisines": "Brazilian, North Eastern",
		"Average_Cost_for_two": 100,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.4,
		"Rating_color": "Green",
		"Rating_text": "Very Good",
		"Votes": 22
	},
	{
		"Restaurant_ID": 6703176,
		"Restaurant_Name": "Veloso",
		"Cuisines": "Brazilian, Bar Food, Beverages",
		"Average_Cost_for_two": 70,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.6,
		"Rating_color": "Dark Green",
		"Rating_text": "Excellent",
		"Votes": 58
	},
	{
		"Restaurant_ID": 6713772,
		"Restaurant_Name": "Sainte Marie Gastronomia",
		"Cuisines": "Lebanese, Arabian",
		"Average_Cost_for_two": 120,
		"Currency": "Brazilian Real(R$)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 4.1,
		"Rating_color": "Green",
		"Rating_text": "Very Good",
		"Votes": 11
	},
	{
		"Restaurant_ID": 17284404,
		"Restaurant_Name": "Austin's BBQ and Oyster Bar",
		"Cuisines": "BBQ, Burger, Seafood",
		"Average_Cost_for_two": 25,
		"Currency": "Dollar($)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 3.3,
		"Rating_color": "Orange",
		"Rating_text": "Average",
		"Votes": 35
	},
	{
		"Restaurant_ID": 17284203,
		"Restaurant_Name": "BJ's Country Buffet",
		"Cuisines": "American, BBQ",
		"Average_Cost_for_two": 10,
		"Currency": "Dollar($)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 3.3,
		"Rating_color": "Orange",
		"Rating_text": "Average",
		"Votes": 25
	},
	{
		"Restaurant_ID": 17284105,
		"Restaurant_Name": "Cookie Shoppe",
		"Cuisines": "",
		"Average_Cost_for_two": 0,
		"Currency": "Dollar($)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 3.4,
		"Rating_color": "Orange",
		"Rating_text": "Average",
		"Votes": 34
	},
	{
		"Restaurant_ID": 17284302,
		"Restaurant_Name": "El Vaquero Mexican Restaurant",
		"Cuisines": "Mexican",
		"Average_Cost_for_two": 0,
		"Currency": "Dollar($)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 3.4,
		"Rating_color": "Orange",
		"Rating_text": "Average",
		"Votes": 45
	},
	{
		"Restaurant_ID": 17284397,
		"Restaurant_Name": "Elements Coffee Co - Northwest",
		"Cuisines": "Coffee and Tea, Sandwich",
		"Average_Cost_for_two": 10,
		"Currency": "Dollar($)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 3.4,
		"Rating_color": "Orange",
		"Rating_text": "Average",
		"Votes": 26
	},
	{
		"Restaurant_ID": 17284211,
		"Restaurant_Name": "Pearly's Famous Country Cookng",
		"Cuisines": "",
		"Average_Cost_for_two": 0,
		"Currency": "Dollar($)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 3.4,
		"Rating_color": "Orange",
		"Rating_text": "Average",
		"Votes": 36
	},
	{
		"Restaurant_ID": 17284094,
		"Restaurant_Name": "Chick-fil-A",
		"Cuisines": "Fast Food",
		"Average_Cost_for_two": 10,
		"Currency": "Dollar($)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 3.5,
		"Rating_color": "Yellow",
		"Rating_text": "Good",
		"Votes": 67
	},
	{
		"Restaurant_ID": 17284409,
		"Restaurant_Name": "Guang Zhou Chinese Restaurant",
		"Cuisines": "Asian, Chinese, Vegetarian",
		"Average_Cost_for_two": 10,
		"Currency": "Dollar($)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 3.9,
		"Rating_color": "Yellow",
		"Rating_text": "Good",
		"Votes": 141
	},
	{
		"Restaurant_ID": 17284139,
		"Restaurant_Name": "Harvest Moon",
		"Cuisines": "Pizza, Bar Food, Sandwich",
		"Average_Cost_for_two": 25,
		"Currency": "Dollar($)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 3.7,
		"Rating_color": "Yellow",
		"Rating_text": "Good",
		"Votes": 147
	},
	{
		"Restaurant_ID": 17284403,
		"Restaurant_Name": "Henry Campbell's Steakhouse",
		"Cuisines": "Steak, Tapas, Bar Food",
		"Average_Cost_for_two": 70,
		"Currency": "Dollar($)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 3.5,
		"Rating_color": "Yellow",
		"Rating_text": "Good",
		"Votes": 51
	},
	{
		"Restaurant_ID": 17284145,
		"Restaurant_Name": "Hong Kong Cafe",
		"Cuisines": "Chinese, Seafood, Vegetarian",
		"Average_Cost_for_two": 25,
		"Currency": "Dollar($)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 3.6,
		"Rating_color": "Yellow",
		"Rating_text": "Good",
		"Votes": 88
	},
	{
		"Restaurant_ID": 17284150,
		"Restaurant_Name": "House of China Restaurant II",
		"Cuisines": "Chinese",
		"Average_Cost_for_two": 10,
		"Currency": "Dollar($)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 3.8,
		"Rating_color": "Yellow",
		"Rating_text": "Good",
		"Votes": 153
	},
	{
		"Restaurant_ID": 17284158,
		"Restaurant_Name": "Jimmie's Hot Dogs",
		"Cuisines": "",
		"Average_Cost_for_two": 10,
		"Currency": "Dollar($)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 3.9,
		"Rating_color": "Yellow",
		"Rating_text": "Good",
		"Votes": 160
	},
	{
		"Restaurant_ID": 17284175,
		"Restaurant_Name": "Locos Grill & Pub",
		"Cuisines": "American, Burger, Sandwich",
		"Average_Cost_for_two": 25,
		"Currency": "Dollar($)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 3.5,
		"Rating_color": "Yellow",
		"Rating_text": "Good",
		"Votes": 57
	},
	{
		"Restaurant_ID": 17284179,
		"Restaurant_Name": "Longhorn Steakhouse",
		"Cuisines": "American, Steak",
		"Average_Cost_for_two": 25,
		"Currency": "Dollar($)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 3.5,
		"Rating_color": "Yellow",
		"Rating_text": "Good",
		"Votes": 58
	},
	{
		"Restaurant_ID": 17284197,
		"Restaurant_Name": "Mikata Japanese Steakhouse",
		"Cuisines": "Japanese, Steak, Sushi",
		"Average_Cost_for_two": 40,
		"Currency": "Dollar($)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 3.6,
		"Rating_color": "Yellow",
		"Rating_text": "Good",
		"Votes": 115
	},
	{
		"Restaurant_ID": 17284241,
		"Restaurant_Name": "Shogun Japanese Steak House",
		"Cuisines": "Japanese, Steak, Sushi",
		"Average_Cost_for_two": 40,
		"Currency": "Dollar($)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 3.5,
		"Rating_color": "Yellow",
		"Rating_text": "Good",
		"Votes": 51
	},
	{
		"Restaurant_ID": 17284390,
		"Restaurant_Name": "The Catch Seafood Room & Oyster Bar",
		"Cuisines": "Seafood, Tapas, Bar Food",
		"Average_Cost_for_two": 40,
		"Currency": "Dollar($)",
		"Has_Table_booking": "No",
		"Has_Online_delivery": "No",
		"Aggregate_rating": 3.8,
		"Rating_color": "Yellow",
		"Rating_text": "Good",
		"Votes": 250
	}
];